#pragma once
// Generated table of setup UI strings (简体 / 繁體 / English).

namespace pulse::setup {

enum class Lang { ZhHans = 0, ZhHant = 1, En = 2 };

enum class Str {
    WindowTitle,
    Tagline,
    Install,
    Upgrade,
    InstallTo,
    Needs,
    Agree,
    License,
    Custom,
    SecLocation,
    AppDir,
    AppDirSub,
    Browse,
    SpaceFree,
    SecSearch,
    OptIndex,
    Recommended,
    OptIndexSub,
    IndexDir,
    IndexDirSub,
    SecOther,
    OptStartup,
    OptStartupSub,
    OptDesktop,
    OptDesktopSub,
    Back,
    Cancel,
    On,
    Off,
    StepExtract,
    StepShortcuts,
    StepIndex,
    StepVerbs,
    StepFinish,
    S1Title,
    S1Text,
    S2Title,
    S2Text,
    S3Title,
    S3Text,
    SearchDemo,
    DoneTitle,
    DoneSub,
    DoneSubNoIndex,
    DoneTitleUp,
    DoneSubUp,
    SumIndex,
    SumIndexFailed,
    SumMenu,
    SumStart,
    Close,
    Launch,
    BusyTitle,
    BusyText,
    Retry,
    CancelTitle,
    CancelText,
    KeepInstalling,
    CancelYes,
    ErrorTitle,
    ErrorRolledBack,
    OpenLog,
    BadDir,
    NoSpace,
    Minimize,
    UnWindowTitle,
    UnTitle,
    UnSub,
    UnClean,
    UnCleanSub,
    UnService,
    UnServiceOn,
    UnServiceNone,
    UnBtn,
    UnDone,
    UnDoneReboot,
    UnFailed,
    UnBusyText,
    IntegrationIncomplete,
    IntegrationFailed,
    Count
};

Lang DetectLanguage(const wchar_t* inno_lang);  // /LANG=chinesesimp|chinesetrad|english or system UI language
const wchar_t* Text(Lang lang, Str id);

}  // namespace pulse::setup
